---
title: "Actividad 1 - Métodos y Simulación Estadística"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#FFFFFF"
      fg: "#034A94" 
      primary: "#034A94"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
library(ggplot2)
library(paqueteMET)

data("CarreraLuz22")
```

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Chart A

```{r}
ggplot(CarreraLuz22, aes(y=timerun/60, x=categoria))+
  geom_jitter(color="#034A94", size=1, alpha=0.9)

```

### Chart B

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart C

```{r}
ggplot(CarreraLuz22, aes(x = categoria, y = timerun/60 )) +
  geom_boxplot(aes(fill = categoria)) + 
  # facet_wrap(~sex, ncol=1, labeller = labeller(dose = etiquetas))+
  labs(title = "", y= "tiempo - min", x= "categorías")+
  scale_fill_brewer() +
  #scale_fill_manual(values = c("#00070D", "#012447", "#034A94", "#0570E1", "#3998FB","#37B6FC"))+
  theme(legend.position = "none")
```

### Chart D

```{r}

```

